apiVersion: v1
kind: Service
metadata:
  name: wood-api-service
spec:
  type: NodePort
  selector:
    app: wood-api                 
  ports:
    - protocol: TCP
      port: 80                      # The Service's internal cluster port
      targetPort: 8080              # The target port in the Pod/Container
      nodePort: 30083

