apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-apps-monolith
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/patakib/kind-argocd.git
    targetRevision: monolith-one-app
    path: sample-apps

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
